// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJkBoo4R7f3f1wyOFmzHxC-mshPfofnJQ',
    appId: '1:197851462902:web:cf8f03cde6d850f932c0d7',
    messagingSenderId: '197851462902',
    projectId: 'learn-crud-a9807',
    authDomain: 'learn-crud-a9807.firebaseapp.com',
    storageBucket: 'learn-crud-a9807.firebasestorage.app',
    measurementId: 'G-D0ZTM7D409',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAte2njeHFPaAEZRqHS5jYzagIvyJXVnMg',
    appId: '1:197851462902:android:c5c74f5175d9104432c0d7',
    messagingSenderId: '197851462902',
    projectId: 'learn-crud-a9807',
    storageBucket: 'learn-crud-a9807.firebasestorage.app',
  );
}
